version: "3.8"
services:
  telerealm:
    build:
      context: .
      dockerfile: dockerfile
    container_name: telerealm
    ports:
      - "7777:7777"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    env_file:
      - .env
